baseURL = 'https://migus.org/'
enableEmoji = true
enableRobotsTXT = true
languageCode = 'en-us'
title = 'migus.org'
author = 'Adam Migus'
copyright = '2026 Adam Migus'
[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
  [markup.highlight]
    style = 'rrt'
[params]
  charset = 'utf-8'
  description = 'Adam Migus — software engineer and computer scientist'

[services]
  [services.googleAnalytics]
    id = 'G-0H4BE185DF'
