name = "Its Business"
license = "MIT"
licenselink = "https://github.com/amigus/hugo-its-business/blob/main/LICENSE"
description = "A clean, simple Hugo theme for personal and business sites"
homepage = "https://github.com/amigus/hugo-its-business"
demosite = "https://migus.org"
tags = ["blog", "personal", "business", "tailwind", "responsive"]
features = ["responsive", "tailwindcss", "emoji support", "syntax highlighting"]
min_version = "0.147.0"

[author]
  name = "Adam Migus"
  homepage = "https://migus.org"
